# Site settings
title: JRowing.com
tag_text: jrowing.com
description: A place for Physics Education and general geekery
url: "https://www.jrowing.com" # base URL for your site ie. "https://www.example.com"
baseurl: "" # subpath for base of site, leave blank if hosting at root

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
